// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://thzxkofmzrwmaivkorfj.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoenhrb2ZtenJ3bWFpdmtvcmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2NzI5OTMsImV4cCI6MjA0ODI0ODk5M30.lzuBCB8biH94KBaFzQGmQlgVy4Y_HCwSyTvfBEcJWbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);